### ISSUE TITLE
Decide format and placement of versioning information

### ISSUE THREAD

**Issue by sshine** [exercism/tcl#10]
For #5 and #9 I've gone with [`set version 1.2.0.0`](https://github.com/exercism/tcl/pull/9/files#diff-eca342f6f9bf95f026ee2c99ed7854feR2) so that it can be extracted with:

```
tclsh <<< 'source test.tcl; puts $version'
```

and so that it is distributed with the handout files.

@glennj: In #9 you requested that `.meta/version` be used (instead / in addition?). Do you have an example of a track that uses `.meta/version`, and does this track have a mechanism for distributing it to the student? Or are you thinking ahead wrt. exercism/discussions#239?

As I understand, exercism/discussions#239 has not reached any consensus for a standard on the placement of such a version number; if this were `.meta/version`, @NobbZ [who suggested it](https://github.com/exercism/discussions/issues/239#issuecomment-506046685) also said he'd have them in the Erlang dependency file.

**Comment by glennj** [comment]
The bash track uses it, but it's not downloaded to the student.
However, I do agree that putting it into the test file is preferable, as it adds visibility.

**Comment by sshine** [comment]
The Haskell track has a 4th part to the version which gets bumped every time files that tests are updated. This means we can keep track of differences in tests when they don't reflect an update to canonical tests.

But since there is no consensus about the format of `.meta/version` in exercism/discussions#239 yet, we cannot really assume that a version like 1.2.0.0 can go into that file. Curious as to how many tracks that employ `.meta/version`:

```bash
all-tracks $ for d in *; do if [ -d $d ]; then echo -n "$d: "; find $d -name version | wc -l; fi; done | grep -vP '0$'
bash: 85
java: 99
kotlin: 58
```

Going over the discussion in exercism/discussions#239 again, I suspect that `.meta/version` with x.y.z in it is the right way to go, and additionally having `set version x.y.z.s` in test.tcl is also nice as we can have a 4th component.

If you agree to have both, we can make a small to-do list:

- [ ] Add `.meta/version` to `hello-world` and `two-fer` (#9).
- [ ] Add CI hook that fails if changes are made to test.tcl and 4th component isn't bumped.
- [ ] Add CI hook that fails if `.meta/version` is not in sync with `set version ...` of test.tcl.
