### ISSUE TITLE
Decide the behavior of tests that fail

### ISSUE THREAD

**Issue by sshine** [exercism/tcl#11]
When a test case fails, should it fail fast? Here are [two ideas](https://github.com/exercism/tcl/issues/3#issuecomment-480903374) for a stub that can be placed in each test file. Deciding on this early has the advantage that we will not need to refactor files as we add more exercises. A necessary side-effect of picking a method of failure is to have the test suite `exit 1` so that Travis CI will register failing tests as errors in #8.

**Comment by glennj** [comment]
I'm not quite sure I grok the intent here: will this abort the test suite on the first failing test?

**Comment by sshine** [comment]
Failing fast will. This is the default for e.g. Haskell and Ruby tracks.

This is supposedly a TDD thing. I do it at work when debugging, too.

**Comment by sshine** [comment]
I will propose that we add the following bit to our each exercise test:

```tcl
proc test args {
    if {$::tcltest::numTests(Failed) > 0} {
        puts "**** Exit on first failure"
        exit 1
    }
    uplevel [list ::tcltest::test {*}$args]
}
```

**Comment by glennj** [comment]
I've had to let this percolate for a couple of days. My preference is to run all the tests. I'd suggest we provide a way to give control to the user. This is pretty ugly, but how about:
```tcl
if {!( [info exists env(TCLTEST_RUN_ALL)] 
    && [string is boolean -strict $env(TCLTEST_RUN_ALL)]
    && $env(TCLTEST_RUN_ALL)
)} {
    proc test args {
        if {$::tcltest::numTests(Failed) > 0} {
            puts "**** Exit on first failure"
            exit 1
        }
        uplevel [list ::tcltest::test {*}$args]
    }
}
```
Unless there is an environment variable named TCLTEST_RUN_ALL that contains a valid Tcl boolean true value, we will redefine `test`

**Comment by sshine** [comment]
How about just `RUN_ALL`?

**Comment by sshine** [comment]
I realize that exiting prematurely means that the bottom header is not printed:

    test.tcl:	Total	3	Passed	0	Skipped	2	Failed	1
