### ISSUE TITLE
Maintain list of completed/in progress/pending exercises

### ISSUE THREAD

**Issue by glennj** [exercism/tcl#23]
AFter I jumped into the bash track and started porting a lot of exercises, we found that the track map needed some rearranging. While that process is still in progress, I did put together the following google spreadsheet to keep track of what we have and where we should go: https://docs.google.com/spreadsheets/d/14c1oovaMJeHvxBWpCk6BqX_XYqNBgLHfQ1WKsM-zye8/edit#gid=537059368

I think something similar would be beneficial while we are building the Tcl track. I'm thinking primarily, we'll be able to figure out:
* who will be working on them (we don't want to be working on the same ones)
* what likely tags they will have
* how they will nest in sensible groups.

If you agree, I'll create such a sheet for Tcl

**Comment by sshine** [comment]
I was honestly just thinking of porting the exercises I felt like.

I got a little drowned in doing a top-down re-design of the Haskell track.

But if you like, you should make that sheet and start filling it out.

I'll probably just keep porting exercises that either you recommend or that I fancy for some reason.

**Comment by sshine** [comment]
But we should certainly coordinate which exercises we port and supply reasons for doing so. :-)

**Comment by glennj** [comment]
Proposed track roadmap: https://docs.google.com/spreadsheets/d/19VdB52hf3iRY2U_QpFn54CcLNXp8wlqq98y99X89sUA/edit?usp=sharing

Ordered by order of core exercises, and nested side exercises get unlocked accordingly.

**Comment by glennj** [comment]
I see you've added a WIP PR. I have some more exercises queued up in my fork --  https://github.com/glennj/tcl/branches

It seems that it would be better to add my exercises as PRs for visibility.

**Comment by sshine** [comment]
Yup! Or we could post here which ones we intend to begin with.

**Comment by glennj** [comment]
As you can see by the PR queue, I can get into sprints where they come fast and furious.

**Comment by sshine** [comment]
I'm putting a lock on:
- rna-transcription
- yacht

which seem to be some of the first side exercises according to your proposed roadmap.

**Comment by sshine** [comment]
@glennj: @iHiD suggested we might enable the Tcl track on https://exercism.io/my/tracks/tcl for testing it before announcing it and linking to it from the front page. According to your roadmap spreadsheet, we're only two short from having all core exercises: Tournament (#49) and Bank Account, which I can see on your [`port/bank-account`](https://github.com/glennj/tcl/commit/09f50c8cb2d3a0f13f6eb13db1b5a4aff199341d) is almost done (short of some thread tests).

I wonder:
 - Do you release exercises one at a time to avoid merge conflicts in config.json?
 - Where would you like to set the bar for a test run; having core exercises?

**Comment by glennj** [comment]
1. "one at a time" -- that's how the bash maintainers asked me to do it, so they could have a look at each exercise PR. Since I've been forging ahead implementing the exercises, I've been wanting your input on how to proceed. One-by-one is simpler for merging. Submitting a PR for *all* the side exercises for each core one would not create merge issues since they all get lumped together in the config.json however that makes for bigger review tasks.  What would you prefer?

2. all the core exercises would make for the minimal bar for entry. For release, we'd want the first 3 . or 4 core exercises to have their side exercises available.

3. threading part. I do need to revisit this to figure out how to allow the threads to access the same object.  Do you have any experience using threads in Tcl?

**Comment by glennj** [comment]
The [Tcl Roadmap google sheet](https://docs.google.com/spreadsheets/d/19VdB52hf3iRY2U_QpFn54CcLNXp8wlqq98y99X89sUA/edit#gid=1704526598) will remain.

The [notes-on-unimplemented-exercises.md](https://github.com/exercism/tcl/blob/master/notes-on-unimplemented-exercises.md) file documents the reasons for the remaining unimplemented exercises.
