### ISSUE TITLE
CI: More validation checks for exercises

### ISSUE THREAD

**Issue by sshine** [exercism/tcl#28]
- [x] Check that for each exercise in `exercises/`, there's a proper entry in `config.json`
- [x] Check that for each exercise in `config.json`, there's a directory in `exercises/`
- [x] Check that exercise files have the proper file permissions

**Comment by glennj** [comment]
Some other tracks use a "deprecated" key in the config.json. Since Tcl track is brand new, I don't see us deprecating any exercises in the foreseeable future, but that might be a factor down the road. If you want to think about that now, that would affect the second item.

**Comment by sshine** [comment]
Thanks for pointing that out!

**Comment by glennj** [comment]
file permissions standardized in #115

**Comment by glennj** [comment]
For items 1 and 2, `configlet lint .` has no errors.
