### ISSUE TITLE
Roll out alpha

### ISSUE THREAD

**Issue by sshine** [exercism/tcl#55]
@iHiD suggested that we enable the Tcl track without linking to it on the front page.

Now that most of the core exercises are done, we could do that and get some initial feedback.

Are you up for this, @glennj?

**Comment by glennj** [comment]
You bet. Let's do it.

As you may be aware, I have a large backlog of side exercises ready to add (https://github.com/glennj/tcl/branches). Are you ready for another flow of pull requests?

**Comment by sshine** [comment]
Yes, keep 'em rolling!

fre. 8. nov. 2019 17.31 skrev Glenn Jackman <notifications@github.com>:

**Comment by sshine** [comment]
@iHiD: Can we get the Tcl track on the website soon?

Glenn has pushed quite a few exercises at this point.

**Comment by iHiD** [comment]
Awesome. Yep! Just need a PR for [this](https://github.com/exercism/tcl/blob/master/config.json#L4) when y'all ready.

**Comment by iHiD** [comment]
Sorry. I misunderstood this. I thought the track was already (automatically) in alpha. I've now added it to the website and you can see it at https://exercism.io/tracks/tcl but have reverted the `active: true`

Once it's ready (description, code-snippet, etc) please re PR the active: true, which puts it live on the front page etc.

**Comment by glennj** [comment]
@iHiD I joined the Tcl track, and now "Oh dear, something's not working here. Sorry about that."

**Comment by iHiD** [comment]
@glennj Hmm, it hadn't synced properly for some reason. I've manually kicked it. How's that now?

**Comment by glennj** [comment]
That's it. Thanks.

@sshine in mentored mode,  none of the exercises are active, I presume because there's no mentors. I'll add myself to that list.

**Comment by iHiD** [comment]
@glennj Ah - you got caught in a weird state by joining the track before any exercises existed. Work now? I've just joined and looks good to me.

**Comment by glennj** [comment]
@iHiD yes all fine.
